# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Fterm < Formula
  desc "fTerm is a CLI tool for managing shortcuts."
  homepage "https://github.com/bedirhangull/fterm"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/bedirhangull/fterm/releases/download/v0.2.0/fTerm_Darwin_x86_64.tar.gz"
      sha256 "05360481f1c149f460c87091f60692ef2b062d7bfc41703fb2bfc77487801c1a"

      def install
        bin.install "fterm"
      end
    end
    on_arm do
      url "https://github.com/bedirhangull/fterm/releases/download/v0.2.0/fTerm_Darwin_arm64.tar.gz"
      sha256 "3c3aefb21adc3ae68c0f32dd4b0f4c1bc37d1a00e42f26d551d4177de441d275"

      def install
        bin.install "fterm"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bedirhangull/fterm/releases/download/v0.2.0/fTerm_Linux_x86_64.tar.gz"
        sha256 "b153c5c631f9b1234915650e47d9a266a1dc9052b71ecad890efbc87ce3833e1"

        def install
          bin.install "fterm"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/bedirhangull/fterm/releases/download/v0.2.0/fTerm_Linux_arm64.tar.gz"
        sha256 "76e0be4a743a3b7cea3bc28bb6b5a83402458b1ec6854118b6a62d1df7991b3a"

        def install
          bin.install "fterm"
        end
      end
    end
  end
end
